name: Build Kernel M14x
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential flex bison libssl-dev libelf-dev clang llvm lld

      - name: Setup Toolchain
        run: |
          # Samsung M14 usually requires a specific Clang/GCC version
          git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9 toolchain

      - name: Build Kernel
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=$(pwd)/toolchain/bin/aarch64-linux-android-
          make m146b_defconfig # Replace with your actual defconfig name
          make -j$(nproc)
        
      - name: Upload Kernel Image
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-Image
          path: arch/arm64/boot/Image.gz-dtb
          
